config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"
  get "/articles", to: "articles#index"
  # get "/articles/new", to: "articles#new"
  # get "/articles/:id", to: "articles#show"
  get "/articles/tinh", to: "articles#tinh"
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # include Visible
  has_many :comments
  #một article có thể có nhiều comments

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/concerns/visible.rb
# module Visible
#   def archived?
#     status == 'archived'
#   end
# end

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  # included do
  #   validates :status, inclusion: { in: VALID_STATUSES }
  # end

  # def archived?
  #   status == 'archived'
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    #nạp cơ sở dữ liệu vào controller
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end
  def tinh
  end

  def create
    # @article = Article.new(params.require(:article).permit(:title, :body))
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      puts ("============== #{params} sadaaa+++++++++++++++++++++++++++++++")
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)  #article/{article.id}
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: xxx do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% xxx.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% xxx.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<!-- <%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %> -->

<h1>Edit Article</h1>

<%= render "form", xxx: @article %> 

app/views/articles/index.html.erb
<p>Từ trên cao t nhìn xuống</p>
<strong>Helloooooooooooooooooooooo</strong>
<ul>
  
<!-- rails tag được viết trong thẻ như dưới--
  nó k cho comment thẻ rails-->
  <!-- xử lý và lấy dữ liệu như này -->
  <% @articles.each do |article| %>
    <li>
      <a href="<%= article_url(article) %>">
        <%= article.title %>
      </a>
    </li>
    <li>
      <%= article.body %>
    </li>
  <% end %>
  <%= link_to "New Article", new_article_path %>
  <!-- http://127.0.0.1:3000/articles/new -->
</ul>

app/views/articles/new.html.erb
<!-- <h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %> -->

<!-- <form action="/articles" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="...">

  <div>
    <label for="article_title">Title</label><br>
    <input type="text" name="article[title]" id="article_title">
  </div>

  <div>
    <label for="article_body">Body</label><br>
    <textarea name="article[body]" id="article_body"></textarea>
  </div>

  <div>
    <input type="submit" name="commit" value="Create Article" data-disable-with="Create Article">
  </div>
</form> -->

<h1>New Article</h1>

<%= render "form", xxx: @article %> 

app/views/articles/show.html.erb
<h1><%=@article.title %></h1>

<p><%=@article.body %></p>

<ul>
  <li>
    <a href='<%=@article.id%>/edit'>Edit</a>
  </li>
  <li><%= link_to "Destroy", article_path(@article),
    method: :delete,
    data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>
<%=render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/articles/tinh.html.erb
<h1>Tịnh-----></h1>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hirails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>